receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true    
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
  debug:      

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, zipkin, otlp]
